looper:
  build: .
  ports: 
    - "6000:6000"
  restart: always
  environment:
    - REGISTRY_HOST
    - SERVICE_HOST
test:
  build: .
  command: echo "No tests defined"
coverage:
  build: .
  command: echo "No coverage defined"
